### ISSUE TITLE
رد شدن برنامه به دلیل سیاست حفظ حریم خصوصی تپسل 

### ISSUE THREAD

**Issue by Meere43** [tapsellorg/TapsellPlusSDK-AndroidSample#77]
از نسخه 2.2.3 استفاده می کنم، در زمان انتشار در گوگل پلی بهم خطا داده شده درباره اینکه privacy policy تپسل به درستی نوشته نشده

برای دلیل رد شدن این را ایمیل کردن:
```
We found an issue in the following area(s):

Version code 1: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: ir.tapsell.sdk:tapsell-sdk-android, ir.tapsell.sdk:tapsell-sdk-unity

To bring your app into compliance, follow these steps:

ir.tapsell.sdk:tapsell-sdk-android ir.tapsell.sdk:tapsell-sdk-android: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
ir.tapsell.sdk:tapsell-sdk-unity ir.tapsell.sdk:tapsell-sdk-unity: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
```

در مستندات هیچ جا گفته نشده که چه متنی در رابطه با privacy policy برنامه باید قرار داده شود. این مشکل از طرف شما هست یا من باید متن مشخصی از طرف شما در این قسمت قرار بدهم؟

**Comment by MortezaNedaei** [comment]
باید در کنسول **GooglePlay** بخش `Data safety` > `Manage`  و بخش `Device or other IDs` اطلاعات مربوط به دیتا را تکمیل کنید
برای بررسی بیشتر از لینک های زیر کمک بگیرید:

[Stackoverflow](https://stackoverflow.com/a/71234298/8291919) | [Google Support](https://support.google.com/googleplay/android-developer/thread/215148990/invalid-data-safety-form-because-of-google-ads?hl=en) | [Google Support](https://support.google.com/googleplay/android-developer/answer/10787469
)

**Comment by Meere43** [comment]
ممنون، امیدوارم برنامه تایید شود.
عجیب هست که قبلا همچین مشکلی نداشتم.

**Comment by Meere43** [comment]
تایید شد
